// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/gphotos/v1)
	GetVersionMetadata(c *gin.Context)

	// (GET /api/gphotos/v1/albums)
	GetAlbums(c *gin.Context, params GetAlbumsParams)

	// (GET /api/gphotos/v1/albums/groups/{group_id})
	GetAlbumsByGroup(c *gin.Context, groupId string, params GetAlbumsByGroupParams)

	// (GET /api/gphotos/v1/albums/users/{user_id})
	GetAlbumsByUser(c *gin.Context, userId string, params GetAlbumsByUserParams)

	// (GET /api/gphotos/v1/albums/{album_id}/permissions)
	GetAlbumPermissions(c *gin.Context, albumId string, params GetAlbumPermissionsParams)

	// (GET /api/gphotos/v1/auth/callback)
	GetApiGphotosV1AuthCallback(c *gin.Context, params GetApiGphotosV1AuthCallbackParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(c *gin.Context)

// GetVersionMetadata operation middleware
func (siw *ServerInterfaceWrapper) GetVersionMetadata(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetVersionMetadata(c)
}

// GetAlbums operation middleware
func (siw *ServerInterfaceWrapper) GetAlbums(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlbumsParams

	// ------------- Optional query parameter "sort" -------------
	if paramValue := c.Query("sort"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "sort", c.Request.URL.Query(), &params.Sort)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter sort: %s", err)})
		return
	}

	// ------------- Optional query parameter "offset" -------------
	if paramValue := c.Query("offset"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter offset: %s", err)})
		return
	}

	// ------------- Optional query parameter "limit" -------------
	if paramValue := c.Query("limit"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter limit: %s", err)})
		return
	}

	// ------------- Optional query parameter "filter" -------------
	if paramValue := c.Query("filter"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "filter", c.Request.URL.Query(), &params.Filter)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter filter: %s", err)})
		return
	}

	// ------------- Optional query parameter "personal" -------------
	if paramValue := c.Query("personal"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "personal", c.Request.URL.Query(), &params.Personal)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter personal: %s", err)})
		return
	}

	// ------------- Optional query parameter "shared" -------------
	if paramValue := c.Query("shared"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "shared", c.Request.URL.Query(), &params.Shared)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter shared: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetAlbums(c, params)
}

// GetAlbumsByGroup operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumsByGroup(c *gin.Context) {

	var err error

	// ------------- Path parameter "group_id" -------------
	var groupId string

	err = runtime.BindStyledParameter("simple", false, "group_id", c.Param("group_id"), &groupId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter group_id: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlbumsByGroupParams

	headers := c.Request.Header

	// ------------- Optional header parameter "cookie" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("cookie")]; found {
		var Cookie string
		n := len(valueList)
		if n != 1 {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Expected one value for cookie, got %d", n)})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "cookie", runtime.ParamLocationHeader, valueList[0], &Cookie)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter cookie: %s", err)})
			return
		}

		params.Cookie = &Cookie

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetAlbumsByGroup(c, groupId, params)
}

// GetAlbumsByUser operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumsByUser(c *gin.Context) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "user_id", c.Param("user_id"), &userId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter user_id: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlbumsByUserParams

	headers := c.Request.Header

	// ------------- Optional header parameter "cookie" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("cookie")]; found {
		var Cookie string
		n := len(valueList)
		if n != 1 {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Expected one value for cookie, got %d", n)})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "cookie", runtime.ParamLocationHeader, valueList[0], &Cookie)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter cookie: %s", err)})
			return
		}

		params.Cookie = &Cookie

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetAlbumsByUser(c, userId, params)
}

// GetAlbumPermissions operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumPermissions(c *gin.Context) {

	var err error

	// ------------- Path parameter "album_id" -------------
	var albumId string

	err = runtime.BindStyledParameter("simple", false, "album_id", c.Param("album_id"), &albumId)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter album_id: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAlbumPermissionsParams

	headers := c.Request.Header

	// ------------- Optional header parameter "cookie" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("cookie")]; found {
		var Cookie string
		n := len(valueList)
		if n != 1 {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Expected one value for cookie, got %d", n)})
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "cookie", runtime.ParamLocationHeader, valueList[0], &Cookie)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter cookie: %s", err)})
			return
		}

		params.Cookie = &Cookie

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetAlbumPermissions(c, albumId, params)
}

// GetApiGphotosV1AuthCallback operation middleware
func (siw *ServerInterfaceWrapper) GetApiGphotosV1AuthCallback(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiGphotosV1AuthCallbackParams

	// ------------- Optional query parameter "code" -------------
	if paramValue := c.Query("code"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "code", c.Request.URL.Query(), &params.Code)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter code: %s", err)})
		return
	}

	// ------------- Optional query parameter "state" -------------
	if paramValue := c.Query("state"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "state", c.Request.URL.Query(), &params.State)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter state: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetApiGphotosV1AuthCallback(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.RouterGroup, si ServerInterface) *gin.RouterGroup {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.RouterGroup, si ServerInterface, options GinServerOptions) *gin.RouterGroup {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	router.GET(options.BaseURL+"/api/gphotos/v1", wrapper.GetVersionMetadata)

	router.GET(options.BaseURL+"/api/gphotos/v1/albums", wrapper.GetAlbums)

	router.GET(options.BaseURL+"/api/gphotos/v1/albums/groups/:group_id", wrapper.GetAlbumsByGroup)

	router.GET(options.BaseURL+"/api/gphotos/v1/albums/users/:user_id", wrapper.GetAlbumsByUser)

	router.GET(options.BaseURL+"/api/gphotos/v1/albums/:album_id/permissions", wrapper.GetAlbumPermissions)

	router.GET(options.BaseURL+"/api/gphotos/v1/auth/callback", wrapper.GetApiGphotosV1AuthCallback)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZTXPbNhP+KxjknfFFr2nHaQ+6pZ3Wk0PjTNr44tF4QHJFIiYBBljaVjX87x0AhCSS",
	"oCjZTg9OT6aIxX4++wBLr2kiy0oKEKjpfE11kkPJ7OP7Iq5L88CK4mpJ5zdr+j8FSzqnb6LtpqjdEV3F",
	"XyHBz7AEBSIB2szWtFKyAoUcrMK4Tu4AzVMKOlG8Qi4FndOKYU7kkmAOxMmQhxwUkBJSzgjXRKNUkNIZ",
	"xVUFdE41Ki4y2sxoooAhpLcsoNeucSlIyhAIF6QW/JEgL0EjKys6o0upSrOTcoE/v9vq5wIhA2UMdFT2",
	"Lez88gEwm7WAp4VMWFiLX5lUIVgJw+3m7eRWZJmtAUco7cO+Uv7F3B6nhCnFVvZ3XpexYLwY+lCrwruw",
	"kZrwqZlRBd9qbgo7v/Hg6FS0jXix2SstxmizaGYOnp9AlVxrLoUNqou3TMm6OjzqSyO+qzCQglqDOlzj",
	"Fw1qr8JmEFkbVyAatnl/sG3XwYEwKpaFgFSXMShfNivTbZGLt8EW0fzvvdqs56b/2BFKUSKzQJuUDSVx",
	"UMswOKaSOOQ0WnWVbmox7Lh+pXfR7qx3tS0CcfQdGISRW+8D5nkafH3HRWih557VanW0O0K+GZZ4wdMh",
	"kYVUARI3rzfcwjKDoxweSQuLJ7Eksiy00TT3rctbdy+y7EQT+SBAEZ5OUpl1YKsuTF+mP18yfUeSXQDZ",
	"fZKYzqOJMJRIXavw5nZhav9oIeyCDFdgJMdH3mI8ZfbTa4t/COdO+vJ8av9xab1/oA4y+UR2dpA7uLy7",
	"zb5rsVUTIstrUEbmD0CWMmQvTJwFJDiI+Yn6Q95P3VoWjXnJxVLaZHMszGpW5RKlScu9i974cP3b5z8/",
	"XH18Y9TKCgSrOJ3Ti9Oz03NzHjLMrfMRq3jUKojuzy3DhWaHDJAYu4qV9grNYlkjYfeMFywugLSWjRMm",
	"Z/ae/SGlc3oJ2K+JKayupNAur2/Pzlx6BYKwpllVFdzd1aOv2l3lXR6noNM3ZfPVjaT1lJQbmRl9d3Y+",
	"DPmjRMJqzEGgcQZSI/mTc7ZHlwIeK0gQUgJKmWM0SWqD22YzEdx4ZGq6MG97eY+21DSaflYUjgvcEZmS",
	"eEWkIjpnClLywDG3xJPUSoFAUsgsg9Rz/6AoLUcaKChWAtr79s3gIJEKSSlTwzrcvPhWg1r5gcGt09lO",
	"cQbnxXAIzcy5tNR2CAnp3CxutR5AYoO7hCFA0mNRTVASBVgrMWK84CV/tu0lLxAUgcdKgaWsEWNO7rj8",
	"LQGTnFSgtBTMA2JEv5cKWYilLICJkAmXIA+svRaczH79i+/Y7y2KA21ecI07dR/rmN0uOZgITp3oxVD0",
	"d6linqYgTkfJ4oNAUKZ0lipauYsRq55fTztU0ka9h0gid02N1vbvLU+bSWoxKTjR7W1jL6moCVL5ZXXp",
	"x6593MJTf1fyUxr3X6m2APP+093bAKoajmoa7dqQJFLe8Q2X5cBSG0dra7M6rvl7Ynnn5jqFZ1+feEVO",
	"fIZOXjeg7RehaN2OLP8unL+49QPRbE36OTaMaj94/QfqPqgdptv8vHJIr+1fg+aoN08Fka0AFYd7sCDz",
	"mTNJIUykjkNJd0oKA/pTR+YYUIfB7KP4AdA8yF8A08eW6XUgusY8SlhRxCy5G0WwFyBLMyPxNNkN0F2T",
	"h5Ct+KWzc33+vsb8V29kArpWPco7GLt8J26qOQKiViUX3AwWGhmODkXt2tEY7Zrrzp6zthfcfw8B/9+2",
	"QuBD7mSLNBZIAZMxS4npYdD4vGHXVIq6rxUa1L0vUa0KOqcRbRbNPwEAAP//GAgBYBEdAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
