// Code generated by go-swagger; DO NOT EDIT.

package albums

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/tupyy/gophoto/models"
)

// GetAlbumsByIDOKCode is the HTTP code returned for type GetAlbumsByIDOK
const GetAlbumsByIDOKCode int = 200

/*GetAlbumsByIDOK return album

swagger:response getAlbumsByIdOK
*/
type GetAlbumsByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserAlbum `json:"body,omitempty"`
}

// NewGetAlbumsByIDOK creates GetAlbumsByIDOK with default headers values
func NewGetAlbumsByIDOK() *GetAlbumsByIDOK {

	return &GetAlbumsByIDOK{}
}

// WithPayload adds the payload to the get albums by Id o k response
func (o *GetAlbumsByIDOK) WithPayload(payload *models.UserAlbum) *GetAlbumsByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get albums by Id o k response
func (o *GetAlbumsByIDOK) SetPayload(payload *models.UserAlbum) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAlbumsByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAlbumsByIDUnauthorizedCode is the HTTP code returned for type GetAlbumsByIDUnauthorized
const GetAlbumsByIDUnauthorizedCode int = 401

/*GetAlbumsByIDUnauthorized Not authenticated.

swagger:response getAlbumsByIdUnauthorized
*/
type GetAlbumsByIDUnauthorized struct {
}

// NewGetAlbumsByIDUnauthorized creates GetAlbumsByIDUnauthorized with default headers values
func NewGetAlbumsByIDUnauthorized() *GetAlbumsByIDUnauthorized {

	return &GetAlbumsByIDUnauthorized{}
}

// WriteResponse to the client
func (o *GetAlbumsByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetAlbumsByIDForbiddenCode is the HTTP code returned for type GetAlbumsByIDForbidden
const GetAlbumsByIDForbiddenCode int = 403

/*GetAlbumsByIDForbidden Forbidden.

swagger:response getAlbumsByIdForbidden
*/
type GetAlbumsByIDForbidden struct {
}

// NewGetAlbumsByIDForbidden creates GetAlbumsByIDForbidden with default headers values
func NewGetAlbumsByIDForbidden() *GetAlbumsByIDForbidden {

	return &GetAlbumsByIDForbidden{}
}

// WriteResponse to the client
func (o *GetAlbumsByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetAlbumsByIDInternalServerErrorCode is the HTTP code returned for type GetAlbumsByIDInternalServerError
const GetAlbumsByIDInternalServerErrorCode int = 500

/*GetAlbumsByIDInternalServerError Internal error.

swagger:response getAlbumsByIdInternalServerError
*/
type GetAlbumsByIDInternalServerError struct {
}

// NewGetAlbumsByIDInternalServerError creates GetAlbumsByIDInternalServerError with default headers values
func NewGetAlbumsByIDInternalServerError() *GetAlbumsByIDInternalServerError {

	return &GetAlbumsByIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetAlbumsByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// GetAlbumsByIDServiceUnavailableCode is the HTTP code returned for type GetAlbumsByIDServiceUnavailable
const GetAlbumsByIDServiceUnavailableCode int = 503

/*GetAlbumsByIDServiceUnavailable Not available.

swagger:response getAlbumsByIdServiceUnavailable
*/
type GetAlbumsByIDServiceUnavailable struct {
}

// NewGetAlbumsByIDServiceUnavailable creates GetAlbumsByIDServiceUnavailable with default headers values
func NewGetAlbumsByIDServiceUnavailable() *GetAlbumsByIDServiceUnavailable {

	return &GetAlbumsByIDServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetAlbumsByIDServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
