// Code generated by go-swagger; DO NOT EDIT.

package albums

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/tupyy/gophoto/models"
)

// GetAlbumsByUserOKCode is the HTTP code returned for type GetAlbumsByUserOK
const GetAlbumsByUserOKCode int = 200

/*GetAlbumsByUserOK list of album shard by 'user_id' with logged user

swagger:response getAlbumsByUserOK
*/
type GetAlbumsByUserOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserAlbums `json:"body,omitempty"`
}

// NewGetAlbumsByUserOK creates GetAlbumsByUserOK with default headers values
func NewGetAlbumsByUserOK() *GetAlbumsByUserOK {

	return &GetAlbumsByUserOK{}
}

// WithPayload adds the payload to the get albums by user o k response
func (o *GetAlbumsByUserOK) WithPayload(payload *models.UserAlbums) *GetAlbumsByUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get albums by user o k response
func (o *GetAlbumsByUserOK) SetPayload(payload *models.UserAlbums) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAlbumsByUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAlbumsByUserUnauthorizedCode is the HTTP code returned for type GetAlbumsByUserUnauthorized
const GetAlbumsByUserUnauthorizedCode int = 401

/*GetAlbumsByUserUnauthorized Not authenticated.

swagger:response getAlbumsByUserUnauthorized
*/
type GetAlbumsByUserUnauthorized struct {
}

// NewGetAlbumsByUserUnauthorized creates GetAlbumsByUserUnauthorized with default headers values
func NewGetAlbumsByUserUnauthorized() *GetAlbumsByUserUnauthorized {

	return &GetAlbumsByUserUnauthorized{}
}

// WriteResponse to the client
func (o *GetAlbumsByUserUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetAlbumsByUserForbiddenCode is the HTTP code returned for type GetAlbumsByUserForbidden
const GetAlbumsByUserForbiddenCode int = 403

/*GetAlbumsByUserForbidden Forbidden.

swagger:response getAlbumsByUserForbidden
*/
type GetAlbumsByUserForbidden struct {
}

// NewGetAlbumsByUserForbidden creates GetAlbumsByUserForbidden with default headers values
func NewGetAlbumsByUserForbidden() *GetAlbumsByUserForbidden {

	return &GetAlbumsByUserForbidden{}
}

// WriteResponse to the client
func (o *GetAlbumsByUserForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetAlbumsByUserInternalServerErrorCode is the HTTP code returned for type GetAlbumsByUserInternalServerError
const GetAlbumsByUserInternalServerErrorCode int = 500

/*GetAlbumsByUserInternalServerError Internal error.

swagger:response getAlbumsByUserInternalServerError
*/
type GetAlbumsByUserInternalServerError struct {
}

// NewGetAlbumsByUserInternalServerError creates GetAlbumsByUserInternalServerError with default headers values
func NewGetAlbumsByUserInternalServerError() *GetAlbumsByUserInternalServerError {

	return &GetAlbumsByUserInternalServerError{}
}

// WriteResponse to the client
func (o *GetAlbumsByUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

// GetAlbumsByUserServiceUnavailableCode is the HTTP code returned for type GetAlbumsByUserServiceUnavailable
const GetAlbumsByUserServiceUnavailableCode int = 503

/*GetAlbumsByUserServiceUnavailable Not available.

swagger:response getAlbumsByUserServiceUnavailable
*/
type GetAlbumsByUserServiceUnavailable struct {
}

// NewGetAlbumsByUserServiceUnavailable creates GetAlbumsByUserServiceUnavailable with default headers values
func NewGetAlbumsByUserServiceUnavailable() *GetAlbumsByUserServiceUnavailable {

	return &GetAlbumsByUserServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetAlbumsByUserServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
