LOG_LEVEL: TRACE

KEYCLOAK_CLIENT_ID: server
KEYCLOAK_CLIENT_SECRET: id
KEYCLOAK_URL: http://localhost:9000
KEYCLOAK_REALM: gophotos
KEYCLOAK_ADMIN_USERNAME: admincli
KEYCLOAK_ADMIN_PWD: admin

POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_USER: resources_admin
POSTGRESQL_PASSWORD: azerty
POSTGRESQL_DBNAME: gophoto

SECRET_KEY: secret
AUTH_CALLBACK_URL: http://localhost:8080/auth/callback/
ENCRYPTION_KEY: dc30f5df5b104d1285114fc1

TEMPLATE_FOLDER: /home/cosmin/projects/perso/gphotos/templates
STATICS_FOLDER: /home/cosmin/projects/perso/gphotos/assets
