LOG_LEVEL: TRACE

KEYCLOAK_CLIENT_ID: server
KEYCLOAK_CLIENT_SECRET: id
KEYCLOAK_URL: http://localhost:9000
KEYCLOAK_REALM: gophotos
KEYCLOAK_ADMIN_USERNAME: admin-cli
KEYCLOAK_ADMIN_PWD: a622bd2b-4fb2-470a-a0a5-000dff8045f6

POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_USER: resources_admin
POSTGRESQL_PASSWORD: azerty
POSTGRESQL_DBNAME: gophoto

MINIO_SERVER_URL: localhost:9010
MINIO_ACCESS_ID: QBQ68V4NVQLJ7I8NO2PH
MINIO_ACCESS_KEY: b5CqDNziR4bm4DlerVVTrE0ks0f+wY2LLzUb9sIB
MINIO_TEMP_BUCKET: temp

SECRET_KEY: secret
AUTH_CALLBACK_URL: http://localhost:8080/auth/callback/
ENCRYPTION_KEY: dc30f5df5b104d1285114fc1

TEMPLATE_FOLDER: /home/cosmin/projects/perso/gphotos/templates
STATICS_FOLDER: /home/cosmin/projects/perso/gphotos/assets
