LOG_LEVEL: TRACE

GIN_MODE: debug
KEYCLOAK_CLIENT_ID: server
KEYCLOAK_CLIENT_SECRET: id
KEYCLOAK_ADMIN_URL: http://localhost:9000
KEYCLOAK_AUTH_URL: http://localhost:9000
KEYCLOAK_REALM: gophotos
KEYCLOAK_ADMIN_USERNAME: admin-cli
KEYCLOAK_ADMIN_PWD: e56e7500-1c16-4055-adaf-7dbefc4e0f0e

POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_USER: resources_admin
POSTGRESQL_PASSWORD: azerty
POSTGRESQL_DBNAME: gophoto

MINIO_SERVER_URL: localhost:9010
MINIO_ACCESS_ID: 0PS3NRI9W9GMTRUTCXS4 
MINIO_ACCESS_KEY: vbejQT80CZWk9z5y+wnxAuIQPrhNQyEj+bXfZovQ
MINIO_TEMP_BUCKET: temp

SECRET_KEY: secret
AUTH_CALLBACK_URL: http://localhost:8080/auth/callback/
ENCRYPTION_KEY: dc30f5df5b104d1285114fc1

TEMPLATE_FOLDER: /home/cosmin/projects/gphotos/templates
STATICS_FOLDER: /home/cosmin/projects/gphotos/static
