version: "3"
services:
  caddy:
    image: caddy:2.4.0-alpine
    container_name: caddy
    networks:
      - gphotos
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ${CADDYFILE}:/etc/caddy/Caddyfile
      - caddy_data:/data
      - ${STATICS}:/static
  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    container_name: postgresql
    networks:
      - gphotos
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PWD}
      POSTGRES_DB: postgres
      VERBOSE: 1
    volumes:
      - ${PG_VOLUME}:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak:15.0.0
    container_name: keycloak
    depends_on:
      - postgres
    networks:
      - gphotos
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - ${KEYCLOAK_REALM_FILE}:/tmp/gophoto-realm.json
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PWD}
      KEYCLOAK_IMPORT: /tmp/gophoto-realm.json
      DB_VENDOR: "postgres"
      DB_ADDR: postgresql
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PWD} 
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    networks:
      - gphotos
    ports:
      - ${MINIO_SERVER_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PWD}
    volumes:
      - ${MINIO_DATA}:/data
  server:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: server
    depends_on:
      - postgres
      - keycloak
      - minio
      - caddy
    networks:
      - gphotos
    environment:
      RESOURCES_FOLDER: ${RESOURCES_FOLDER}
      STATICS_FOLDER: ${STATICS_FOLDER}
    volumes:
      - ${RESOURCES_FOLDER}:/etc/server
    command:
      - serve 
      - --config 
      - /etc/server/.gophoto-prod.yaml  

networks:
  gphotos:

volumes:
  caddy_data:


