version: "3"
services:
  postgres:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: postgresql
    networks:
      - gphotos
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PWD}
      POSTGRES_DB: postgres
      VERBOSE: 1
    volumes:
      - ${PG_VOLUME}:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak:15.0.0
    container_name: keycloak
    depends_on:
      - postgres
    networks:
      - gphotos
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - ${KEYCLOAK_REALM_FILE}:/tmp/gophoto-realm.json
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PWD}
      KEYCLOAK_IMPORT: /tmp/gophoto-realm.json
      DB_VENDOR: "postgres"
      DB_ADDR: postgresql
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: azerty

networks:
  gphotos:

volumes:
  postgresq-gphotos:

