version: "3"
services:
  caddy:
    image: caddy:${CADDY_CUSTOM_VERSION}
    container_name: caddy
    restart: always
    networks:
      - gphotos
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - caddy_data:/data
  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    container_name: postgresql
    restart: always
    networks:
      - gphotos
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PWD}
      POSTGRES_DB: postgres
      VERBOSE: 1
    volumes:
      - ${PG_VOLUME}:/var/lib/postgresql/data
  keycloak:
    image: gophoto-keycloak:15.0.0
    container_name: keycloak
    restart: always
    depends_on:
      - postgres
    networks:
      - gphotos
    ports:
      - ${KEYCLOAK_PORT}:8080
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PWD}
      KEYCLOAK_IMPORT: /tmp/gophoto-realm.json
      DB_VENDOR: "postgres"
      DB_ADDR: postgresql
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${DB_PWD} 
      PROXY_ADDRESS_FORWARDING: "true"
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    networks:
      - gphotos
    ports:
      - ${MINIO_SERVER_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PWD}
    volumes:
      - ${MINIO_DATA}:/data
  server:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: server
    restart: always
    depends_on:
      - postgres
      - keycloak
      - minio
      - caddy
    networks:
      - gphotos
    environment:
      GIN_MODE: release
    command:
      - serve 
      - --config 
      - /conf/.gophoto-prod.yaml  

networks:
  gphotos:

volumes:
  caddy_data:


