// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/tupyy/gophoto/models"
)

// GetAlbumsOKCode is the HTTP code returned for type GetAlbumsOK
const GetAlbumsOKCode int = 200

/*GetAlbumsOK list of albums owned by or shared with the user

swagger:response getAlbumsOK
*/
type GetAlbumsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Albums `json:"body,omitempty"`
}

// NewGetAlbumsOK creates GetAlbumsOK with default headers values
func NewGetAlbumsOK() *GetAlbumsOK {

	return &GetAlbumsOK{}
}

// WithPayload adds the payload to the get albums o k response
func (o *GetAlbumsOK) WithPayload(payload *models.Albums) *GetAlbumsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get albums o k response
func (o *GetAlbumsOK) SetPayload(payload *models.Albums) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAlbumsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
