// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/tupyy/gophoto/models"
)

// GetVersionMetadataOKCode is the HTTP code returned for type GetVersionMetadataOK
const GetVersionMetadataOKCode int = 200

/*GetVersionMetadataOK version metadata

swagger:response getVersionMetadataOK
*/
type GetVersionMetadataOK struct {

	/*
	  In: Body
	*/
	Payload *models.VersionMetadata `json:"body,omitempty"`
}

// NewGetVersionMetadataOK creates GetVersionMetadataOK with default headers values
func NewGetVersionMetadataOK() *GetVersionMetadataOK {

	return &GetVersionMetadataOK{}
}

// WithPayload adds the payload to the get version metadata o k response
func (o *GetVersionMetadataOK) WithPayload(payload *models.VersionMetadata) *GetVersionMetadataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get version metadata o k response
func (o *GetVersionMetadataOK) SetPayload(payload *models.VersionMetadata) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVersionMetadataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetVersionMetadataUnauthorizedCode is the HTTP code returned for type GetVersionMetadataUnauthorized
const GetVersionMetadataUnauthorizedCode int = 401

/*GetVersionMetadataUnauthorized Not authenticated

swagger:response getVersionMetadataUnauthorized
*/
type GetVersionMetadataUnauthorized struct {
}

// NewGetVersionMetadataUnauthorized creates GetVersionMetadataUnauthorized with default headers values
func NewGetVersionMetadataUnauthorized() *GetVersionMetadataUnauthorized {

	return &GetVersionMetadataUnauthorized{}
}

// WriteResponse to the client
func (o *GetVersionMetadataUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetVersionMetadataInternalServerErrorCode is the HTTP code returned for type GetVersionMetadataInternalServerError
const GetVersionMetadataInternalServerErrorCode int = 500

/*GetVersionMetadataInternalServerError unexpected error occured

swagger:response getVersionMetadataInternalServerError
*/
type GetVersionMetadataInternalServerError struct {
}

// NewGetVersionMetadataInternalServerError creates GetVersionMetadataInternalServerError with default headers values
func NewGetVersionMetadataInternalServerError() *GetVersionMetadataInternalServerError {

	return &GetVersionMetadataInternalServerError{}
}

// WriteResponse to the client
func (o *GetVersionMetadataInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
