// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetVersionMetadataHandlerFunc turns a function with the right signature into a get version metadata handler
type GetVersionMetadataHandlerFunc func(GetVersionMetadataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVersionMetadataHandlerFunc) Handle(params GetVersionMetadataParams) middleware.Responder {
	return fn(params)
}

// GetVersionMetadataHandler interface for that can handle valid get version metadata params
type GetVersionMetadataHandler interface {
	Handle(GetVersionMetadataParams) middleware.Responder
}

// NewGetVersionMetadata creates a new http.Handler for the get version metadata operation
func NewGetVersionMetadata(ctx *middleware.Context, handler GetVersionMetadataHandler) *GetVersionMetadata {
	return &GetVersionMetadata{Context: ctx, Handler: handler}
}

/* GetVersionMetadata swagger:route GET /api/gphotos/v1 getVersionMetadata

get inforamtion about available versions

*/
type GetVersionMetadata struct {
	Context *middleware.Context
	Handler GetVersionMetadataHandler
}

func (o *GetVersionMetadata) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetVersionMetadataParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
