// Code generated by go-swagger; DO NOT EDIT.

// Package restapi gphotos
//
//  This API is dedicated to device management.
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /
//  Version: 0.8.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
