// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This API is dedicated to device management.",
    "title": "gphotos",
    "version": "0.8.0"
  },
  "paths": {
    "/api/gphotos/v1": {
      "get": {
        "description": "get inforamtion about available versions",
        "operationId": "getVersionMetadata",
        "responses": {
          "200": {
            "description": "version metadata",
            "schema": {
              "$ref": "#/definitions/VersionMetadata"
            }
          },
          "401": {
            "description": "Not authenticated"
          },
          "500": {
            "description": "unexpected error occured"
          }
        }
      }
    },
    "/api/gphotos/v1/albums": {
      "get": {
        "description": "get all albums owned by or shared with the current logged user",
        "tags": [
          "Albums"
        ],
        "operationId": "getAlbums",
        "responses": {
          "200": {
            "description": "list of albums that can be accessed by the logged user",
            "schema": {
              "$ref": "#/definitions/Albums"
            }
          },
          "401": {
            "description": "Not authenticated."
          },
          "403": {
            "description": "Forbidden."
          },
          "500": {
            "description": "Internal error."
          },
          "503": {
            "description": "Not available."
          }
        }
      }
    },
    "/api/gphotos/v1/albums/users/{user_id}": {
      "get": {
        "description": "get all user's album with the logged user can access",
        "tags": [
          "Albums"
        ],
        "operationId": "getAlbumsByUser",
        "parameters": [
          {
            "type": "string",
            "description": "id of the album's owner",
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "list of album shard by 'user_id' with logged user",
            "schema": {
              "$ref": "#/definitions/UserAlbums"
            }
          },
          "401": {
            "description": "Not authenticated."
          },
          "403": {
            "description": "Forbidden."
          },
          "500": {
            "description": "Internal error."
          },
          "503": {
            "description": "Not available."
          }
        }
      }
    },
    "/api/gphotos/v1/albums/{album_id}": {
      "get": {
        "description": "get album by id",
        "tags": [
          "Albums"
        ],
        "operationId": "getAlbumsByID",
        "parameters": [
          {
            "type": "string",
            "description": "id of the album's owner",
            "name": "album_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "return album",
            "schema": {
              "$ref": "#/definitions/UserAlbum"
            }
          },
          "401": {
            "description": "Not authenticated."
          },
          "403": {
            "description": "Forbidden."
          },
          "500": {
            "description": "Internal error."
          },
          "503": {
            "description": "Not available."
          }
        }
      }
    }
  },
  "definitions": {
    "Album": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "required": [
            "name",
            "created_at",
            "bucket"
          ],
          "properties": {
            "bucket": {
              "description": "path of the bucket where media is stored",
              "type": "string"
            },
            "created_at": {
              "description": "creation date in unix timestamp",
              "type": "integer",
              "format": "int64"
            },
            "description": {
              "description": "description of the album",
              "type": "string"
            },
            "group_permissions": {
              "$ref": "#/definitions/GroupPermissions"
            },
            "location": {
              "description": "location of the album",
              "type": "string"
            },
            "name": {
              "description": "name of the album",
              "type": "string"
            },
            "tags": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Tag"
              }
            },
            "thumbnail": {
              "description": "url of the thumbnail of the album",
              "type": "string"
            },
            "user_permissions": {
              "$ref": "#/definitions/UserPermissions"
            }
          }
        }
      ]
    },
    "Albums": {
      "type": "object",
      "properties": {
        "albums": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/UserAlbum"
          }
        },
        "page": {
          "description": "number of the page",
          "type": "integer",
          "format": "int32"
        },
        "size": {
          "description": "number of album in a page",
          "type": "integer",
          "format": "int32"
        },
        "total": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "Group": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "properties": {
            "members": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ObjectReference"
              }
            },
            "name": {
              "description": "name of the group",
              "type": "string"
            }
          }
        }
      ]
    },
    "GroupPermissions": {
      "type": "object",
      "required": [
        "group",
        "permissions"
      ],
      "properties": {
        "group": {
          "$ref": "#/definitions/ObjectReference"
        },
        "permissions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "ObjectReference": {
      "type": "object",
      "required": [
        "id",
        "kind",
        "href"
      ],
      "properties": {
        "href": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        }
      }
    },
    "Photo": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "properties": {
            "bucket": {
              "description": "bucket where the photo is stored",
              "type": "string"
            },
            "filename": {
              "description": "name of the file",
              "type": "string"
            },
            "thumbnail": {
              "description": "path to the thumbnail of the photo",
              "type": "string"
            }
          }
        }
      ]
    },
    "Photos": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Photo"
      }
    },
    "Tag": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "required": [
            "user_id",
            "name",
            "albums"
          ],
          "properties": {
            "albums": {
              "type": "array",
              "items": {
                "allOf": [
                  {
                    "$ref": "#/definitions/ObjectReference"
                  }
                ]
              }
            },
            "color": {
              "description": "color of the tag in hex format",
              "type": "string"
            },
            "name": {
              "description": "name of the tag",
              "type": "string"
            },
            "user_id": {
              "description": "tag's owner id",
              "type": "string"
            }
          }
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "properties": {
            "page": {
              "description": "number of the page",
              "type": "integer",
              "format": "int32"
            },
            "size": {
              "description": "number of album in a page",
              "type": "integer",
              "format": "int32"
            },
            "tags": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Tag"
              }
            },
            "total": {
              "type": "integer",
              "format": "int32"
            }
          }
        }
      ]
    },
    "User": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "properties": {
            "groups": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ObjectReference"
              }
            },
            "name": {
              "description": "name of the user",
              "type": "string"
            },
            "surname": {
              "description": "surname of the user",
              "type": "string"
            },
            "user_id": {
              "description": "user_id",
              "type": "string"
            }
          }
        }
      ]
    },
    "UserAlbum": {
      "allOf": [
        {
          "$ref": "#/definitions/Album"
        },
        {
          "type": "object",
          "properties": {
            "owner": {
              "$ref": "#/definitions/User"
            }
          }
        }
      ]
    },
    "UserAlbums": {
      "type": "object",
      "properties": {
        "albums": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Album"
          }
        },
        "owner": {
          "$ref": "#/definitions/User"
        },
        "page": {
          "description": "number of the page",
          "type": "integer",
          "format": "int32"
        },
        "size": {
          "description": "number of album in a page",
          "type": "integer",
          "format": "int32"
        },
        "total": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "UserPermissions": {
      "type": "object",
      "required": [
        "user",
        "permissions"
      ],
      "properties": {
        "permissions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      }
    },
    "VersionMetadata": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "properties": {
            "collections": {
              "type": "array",
              "items": {
                "allOf": [
                  {
                    "$ref": "#/definitions/ObjectReference"
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This API is dedicated to device management.",
    "title": "gphotos",
    "version": "0.8.0"
  },
  "paths": {
    "/api/gphotos/v1": {
      "get": {
        "description": "get inforamtion about available versions",
        "operationId": "getVersionMetadata",
        "responses": {
          "200": {
            "description": "version metadata",
            "schema": {
              "$ref": "#/definitions/VersionMetadata"
            }
          },
          "401": {
            "description": "Not authenticated"
          },
          "500": {
            "description": "unexpected error occured"
          }
        }
      }
    },
    "/api/gphotos/v1/albums": {
      "get": {
        "description": "get all albums owned by or shared with the current logged user",
        "tags": [
          "Albums"
        ],
        "operationId": "getAlbums",
        "responses": {
          "200": {
            "description": "list of albums that can be accessed by the logged user",
            "schema": {
              "$ref": "#/definitions/Albums"
            }
          },
          "401": {
            "description": "Not authenticated."
          },
          "403": {
            "description": "Forbidden."
          },
          "500": {
            "description": "Internal error."
          },
          "503": {
            "description": "Not available."
          }
        }
      }
    },
    "/api/gphotos/v1/albums/users/{user_id}": {
      "get": {
        "description": "get all user's album with the logged user can access",
        "tags": [
          "Albums"
        ],
        "operationId": "getAlbumsByUser",
        "parameters": [
          {
            "type": "string",
            "description": "id of the album's owner",
            "name": "user_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "list of album shard by 'user_id' with logged user",
            "schema": {
              "$ref": "#/definitions/UserAlbums"
            }
          },
          "401": {
            "description": "Not authenticated."
          },
          "403": {
            "description": "Forbidden."
          },
          "500": {
            "description": "Internal error."
          },
          "503": {
            "description": "Not available."
          }
        }
      }
    },
    "/api/gphotos/v1/albums/{album_id}": {
      "get": {
        "description": "get album by id",
        "tags": [
          "Albums"
        ],
        "operationId": "getAlbumsByID",
        "parameters": [
          {
            "type": "string",
            "description": "id of the album's owner",
            "name": "album_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "return album",
            "schema": {
              "$ref": "#/definitions/UserAlbum"
            }
          },
          "401": {
            "description": "Not authenticated."
          },
          "403": {
            "description": "Forbidden."
          },
          "500": {
            "description": "Internal error."
          },
          "503": {
            "description": "Not available."
          }
        }
      }
    }
  },
  "definitions": {
    "Album": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "required": [
            "name",
            "created_at",
            "bucket"
          ],
          "properties": {
            "bucket": {
              "description": "path of the bucket where media is stored",
              "type": "string"
            },
            "created_at": {
              "description": "creation date in unix timestamp",
              "type": "integer",
              "format": "int64"
            },
            "description": {
              "description": "description of the album",
              "type": "string"
            },
            "group_permissions": {
              "$ref": "#/definitions/GroupPermissions"
            },
            "location": {
              "description": "location of the album",
              "type": "string"
            },
            "name": {
              "description": "name of the album",
              "type": "string"
            },
            "tags": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Tag"
              }
            },
            "thumbnail": {
              "description": "url of the thumbnail of the album",
              "type": "string"
            },
            "user_permissions": {
              "$ref": "#/definitions/UserPermissions"
            }
          }
        }
      ]
    },
    "Albums": {
      "type": "object",
      "properties": {
        "albums": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/UserAlbum"
          }
        },
        "page": {
          "description": "number of the page",
          "type": "integer",
          "format": "int32"
        },
        "size": {
          "description": "number of album in a page",
          "type": "integer",
          "format": "int32"
        },
        "total": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "Group": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "properties": {
            "members": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ObjectReference"
              }
            },
            "name": {
              "description": "name of the group",
              "type": "string"
            }
          }
        }
      ]
    },
    "GroupPermissions": {
      "type": "object",
      "required": [
        "group",
        "permissions"
      ],
      "properties": {
        "group": {
          "$ref": "#/definitions/ObjectReference"
        },
        "permissions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "ObjectReference": {
      "type": "object",
      "required": [
        "id",
        "kind",
        "href"
      ],
      "properties": {
        "href": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        }
      }
    },
    "Photo": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "properties": {
            "bucket": {
              "description": "bucket where the photo is stored",
              "type": "string"
            },
            "filename": {
              "description": "name of the file",
              "type": "string"
            },
            "thumbnail": {
              "description": "path to the thumbnail of the photo",
              "type": "string"
            }
          }
        }
      ]
    },
    "Photos": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Photo"
      }
    },
    "Tag": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "required": [
            "user_id",
            "name",
            "albums"
          ],
          "properties": {
            "albums": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/TagAlbumsItems0"
              }
            },
            "color": {
              "description": "color of the tag in hex format",
              "type": "string"
            },
            "name": {
              "description": "name of the tag",
              "type": "string"
            },
            "user_id": {
              "description": "tag's owner id",
              "type": "string"
            }
          }
        }
      ]
    },
    "TagAlbumsItems0": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "properties": {
            "page": {
              "description": "number of the page",
              "type": "integer",
              "format": "int32"
            },
            "size": {
              "description": "number of album in a page",
              "type": "integer",
              "format": "int32"
            },
            "tags": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Tag"
              }
            },
            "total": {
              "type": "integer",
              "format": "int32"
            }
          }
        }
      ]
    },
    "User": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "properties": {
            "groups": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ObjectReference"
              }
            },
            "name": {
              "description": "name of the user",
              "type": "string"
            },
            "surname": {
              "description": "surname of the user",
              "type": "string"
            },
            "user_id": {
              "description": "user_id",
              "type": "string"
            }
          }
        }
      ]
    },
    "UserAlbum": {
      "allOf": [
        {
          "$ref": "#/definitions/Album"
        },
        {
          "type": "object",
          "properties": {
            "owner": {
              "$ref": "#/definitions/User"
            }
          }
        }
      ]
    },
    "UserAlbums": {
      "type": "object",
      "properties": {
        "albums": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Album"
          }
        },
        "owner": {
          "$ref": "#/definitions/User"
        },
        "page": {
          "description": "number of the page",
          "type": "integer",
          "format": "int32"
        },
        "size": {
          "description": "number of album in a page",
          "type": "integer",
          "format": "int32"
        },
        "total": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "UserPermissions": {
      "type": "object",
      "required": [
        "user",
        "permissions"
      ],
      "properties": {
        "permissions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      }
    },
    "VersionMetadata": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        },
        {
          "type": "object",
          "properties": {
            "collections": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/VersionMetadataCollectionsItems0"
              }
            }
          }
        }
      ]
    },
    "VersionMetadataCollectionsItems0": {
      "allOf": [
        {
          "$ref": "#/definitions/ObjectReference"
        }
      ]
    }
  }
}`))
}
