// Code generated by go-swagger; DO NOT EDIT.

package albums

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAlbumsByUserParams creates a new GetAlbumsByUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAlbumsByUserParams() *GetAlbumsByUserParams {
	return &GetAlbumsByUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAlbumsByUserParamsWithTimeout creates a new GetAlbumsByUserParams object
// with the ability to set a timeout on a request.
func NewGetAlbumsByUserParamsWithTimeout(timeout time.Duration) *GetAlbumsByUserParams {
	return &GetAlbumsByUserParams{
		timeout: timeout,
	}
}

// NewGetAlbumsByUserParamsWithContext creates a new GetAlbumsByUserParams object
// with the ability to set a context for a request.
func NewGetAlbumsByUserParamsWithContext(ctx context.Context) *GetAlbumsByUserParams {
	return &GetAlbumsByUserParams{
		Context: ctx,
	}
}

// NewGetAlbumsByUserParamsWithHTTPClient creates a new GetAlbumsByUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAlbumsByUserParamsWithHTTPClient(client *http.Client) *GetAlbumsByUserParams {
	return &GetAlbumsByUserParams{
		HTTPClient: client,
	}
}

/* GetAlbumsByUserParams contains all the parameters to send to the API endpoint
   for the get albums by user operation.

   Typically these are written to a http.Request.
*/
type GetAlbumsByUserParams struct {

	/* UserID.

	   id of the album's owner
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get albums by user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAlbumsByUserParams) WithDefaults() *GetAlbumsByUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get albums by user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAlbumsByUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get albums by user params
func (o *GetAlbumsByUserParams) WithTimeout(timeout time.Duration) *GetAlbumsByUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get albums by user params
func (o *GetAlbumsByUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get albums by user params
func (o *GetAlbumsByUserParams) WithContext(ctx context.Context) *GetAlbumsByUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get albums by user params
func (o *GetAlbumsByUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get albums by user params
func (o *GetAlbumsByUserParams) WithHTTPClient(client *http.Client) *GetAlbumsByUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get albums by user params
func (o *GetAlbumsByUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get albums by user params
func (o *GetAlbumsByUserParams) WithUserID(userID string) *GetAlbumsByUserParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get albums by user params
func (o *GetAlbumsByUserParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAlbumsByUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
