// Code generated by go-swagger; DO NOT EDIT.

package albums

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAlbumsByIDParams creates a new GetAlbumsByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAlbumsByIDParams() *GetAlbumsByIDParams {
	return &GetAlbumsByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAlbumsByIDParamsWithTimeout creates a new GetAlbumsByIDParams object
// with the ability to set a timeout on a request.
func NewGetAlbumsByIDParamsWithTimeout(timeout time.Duration) *GetAlbumsByIDParams {
	return &GetAlbumsByIDParams{
		timeout: timeout,
	}
}

// NewGetAlbumsByIDParamsWithContext creates a new GetAlbumsByIDParams object
// with the ability to set a context for a request.
func NewGetAlbumsByIDParamsWithContext(ctx context.Context) *GetAlbumsByIDParams {
	return &GetAlbumsByIDParams{
		Context: ctx,
	}
}

// NewGetAlbumsByIDParamsWithHTTPClient creates a new GetAlbumsByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAlbumsByIDParamsWithHTTPClient(client *http.Client) *GetAlbumsByIDParams {
	return &GetAlbumsByIDParams{
		HTTPClient: client,
	}
}

/* GetAlbumsByIDParams contains all the parameters to send to the API endpoint
   for the get albums by ID operation.

   Typically these are written to a http.Request.
*/
type GetAlbumsByIDParams struct {

	/* AlbumID.

	   id of the album's owner
	*/
	AlbumID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get albums by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAlbumsByIDParams) WithDefaults() *GetAlbumsByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get albums by ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAlbumsByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get albums by ID params
func (o *GetAlbumsByIDParams) WithTimeout(timeout time.Duration) *GetAlbumsByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get albums by ID params
func (o *GetAlbumsByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get albums by ID params
func (o *GetAlbumsByIDParams) WithContext(ctx context.Context) *GetAlbumsByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get albums by ID params
func (o *GetAlbumsByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get albums by ID params
func (o *GetAlbumsByIDParams) WithHTTPClient(client *http.Client) *GetAlbumsByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get albums by ID params
func (o *GetAlbumsByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAlbumID adds the albumID to the get albums by ID params
func (o *GetAlbumsByIDParams) WithAlbumID(albumID string) *GetAlbumsByIDParams {
	o.SetAlbumID(albumID)
	return o
}

// SetAlbumID adds the albumId to the get albums by ID params
func (o *GetAlbumsByIDParams) SetAlbumID(albumID string) {
	o.AlbumID = albumID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAlbumsByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param album_id
	if err := r.SetPathParam("album_id", o.AlbumID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
