// Code generated by go-swagger; DO NOT EDIT.

package albums

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAlbumsParams creates a new GetAlbumsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAlbumsParams() *GetAlbumsParams {
	return &GetAlbumsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAlbumsParamsWithTimeout creates a new GetAlbumsParams object
// with the ability to set a timeout on a request.
func NewGetAlbumsParamsWithTimeout(timeout time.Duration) *GetAlbumsParams {
	return &GetAlbumsParams{
		timeout: timeout,
	}
}

// NewGetAlbumsParamsWithContext creates a new GetAlbumsParams object
// with the ability to set a context for a request.
func NewGetAlbumsParamsWithContext(ctx context.Context) *GetAlbumsParams {
	return &GetAlbumsParams{
		Context: ctx,
	}
}

// NewGetAlbumsParamsWithHTTPClient creates a new GetAlbumsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAlbumsParamsWithHTTPClient(client *http.Client) *GetAlbumsParams {
	return &GetAlbumsParams{
		HTTPClient: client,
	}
}

/* GetAlbumsParams contains all the parameters to send to the API endpoint
   for the get albums operation.

   Typically these are written to a http.Request.
*/
type GetAlbumsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get albums params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAlbumsParams) WithDefaults() *GetAlbumsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get albums params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAlbumsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get albums params
func (o *GetAlbumsParams) WithTimeout(timeout time.Duration) *GetAlbumsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get albums params
func (o *GetAlbumsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get albums params
func (o *GetAlbumsParams) WithContext(ctx context.Context) *GetAlbumsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get albums params
func (o *GetAlbumsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get albums params
func (o *GetAlbumsParams) WithHTTPClient(client *http.Client) *GetAlbumsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get albums params
func (o *GetAlbumsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAlbumsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
