// Code generated by go-swagger; DO NOT EDIT.

package albums

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tupyy/gophoto/models"
)

// GetAlbumsByIDReader is a Reader for the GetAlbumsByID structure.
type GetAlbumsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAlbumsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAlbumsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAlbumsByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAlbumsByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAlbumsByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetAlbumsByIDServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAlbumsByIDOK creates a GetAlbumsByIDOK with default headers values
func NewGetAlbumsByIDOK() *GetAlbumsByIDOK {
	return &GetAlbumsByIDOK{}
}

/* GetAlbumsByIDOK describes a response with status code 200, with default header values.

return album
*/
type GetAlbumsByIDOK struct {
	Payload *models.UserAlbum
}

// IsSuccess returns true when this get albums by Id o k response has a 2xx status code
func (o *GetAlbumsByIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get albums by Id o k response has a 3xx status code
func (o *GetAlbumsByIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get albums by Id o k response has a 4xx status code
func (o *GetAlbumsByIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get albums by Id o k response has a 5xx status code
func (o *GetAlbumsByIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get albums by Id o k response a status code equal to that given
func (o *GetAlbumsByIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAlbumsByIDOK) Error() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums/{album_id}][%d] getAlbumsByIdOK  %+v", 200, o.Payload)
}

func (o *GetAlbumsByIDOK) String() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums/{album_id}][%d] getAlbumsByIdOK  %+v", 200, o.Payload)
}

func (o *GetAlbumsByIDOK) GetPayload() *models.UserAlbum {
	return o.Payload
}

func (o *GetAlbumsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserAlbum)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAlbumsByIDUnauthorized creates a GetAlbumsByIDUnauthorized with default headers values
func NewGetAlbumsByIDUnauthorized() *GetAlbumsByIDUnauthorized {
	return &GetAlbumsByIDUnauthorized{}
}

/* GetAlbumsByIDUnauthorized describes a response with status code 401, with default header values.

Not authenticated.
*/
type GetAlbumsByIDUnauthorized struct {
}

// IsSuccess returns true when this get albums by Id unauthorized response has a 2xx status code
func (o *GetAlbumsByIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get albums by Id unauthorized response has a 3xx status code
func (o *GetAlbumsByIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get albums by Id unauthorized response has a 4xx status code
func (o *GetAlbumsByIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get albums by Id unauthorized response has a 5xx status code
func (o *GetAlbumsByIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get albums by Id unauthorized response a status code equal to that given
func (o *GetAlbumsByIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetAlbumsByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums/{album_id}][%d] getAlbumsByIdUnauthorized ", 401)
}

func (o *GetAlbumsByIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums/{album_id}][%d] getAlbumsByIdUnauthorized ", 401)
}

func (o *GetAlbumsByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAlbumsByIDForbidden creates a GetAlbumsByIDForbidden with default headers values
func NewGetAlbumsByIDForbidden() *GetAlbumsByIDForbidden {
	return &GetAlbumsByIDForbidden{}
}

/* GetAlbumsByIDForbidden describes a response with status code 403, with default header values.

Forbidden.
*/
type GetAlbumsByIDForbidden struct {
}

// IsSuccess returns true when this get albums by Id forbidden response has a 2xx status code
func (o *GetAlbumsByIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get albums by Id forbidden response has a 3xx status code
func (o *GetAlbumsByIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get albums by Id forbidden response has a 4xx status code
func (o *GetAlbumsByIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get albums by Id forbidden response has a 5xx status code
func (o *GetAlbumsByIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get albums by Id forbidden response a status code equal to that given
func (o *GetAlbumsByIDForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetAlbumsByIDForbidden) Error() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums/{album_id}][%d] getAlbumsByIdForbidden ", 403)
}

func (o *GetAlbumsByIDForbidden) String() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums/{album_id}][%d] getAlbumsByIdForbidden ", 403)
}

func (o *GetAlbumsByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAlbumsByIDInternalServerError creates a GetAlbumsByIDInternalServerError with default headers values
func NewGetAlbumsByIDInternalServerError() *GetAlbumsByIDInternalServerError {
	return &GetAlbumsByIDInternalServerError{}
}

/* GetAlbumsByIDInternalServerError describes a response with status code 500, with default header values.

Internal error.
*/
type GetAlbumsByIDInternalServerError struct {
}

// IsSuccess returns true when this get albums by Id internal server error response has a 2xx status code
func (o *GetAlbumsByIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get albums by Id internal server error response has a 3xx status code
func (o *GetAlbumsByIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get albums by Id internal server error response has a 4xx status code
func (o *GetAlbumsByIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get albums by Id internal server error response has a 5xx status code
func (o *GetAlbumsByIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get albums by Id internal server error response a status code equal to that given
func (o *GetAlbumsByIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetAlbumsByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums/{album_id}][%d] getAlbumsByIdInternalServerError ", 500)
}

func (o *GetAlbumsByIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums/{album_id}][%d] getAlbumsByIdInternalServerError ", 500)
}

func (o *GetAlbumsByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAlbumsByIDServiceUnavailable creates a GetAlbumsByIDServiceUnavailable with default headers values
func NewGetAlbumsByIDServiceUnavailable() *GetAlbumsByIDServiceUnavailable {
	return &GetAlbumsByIDServiceUnavailable{}
}

/* GetAlbumsByIDServiceUnavailable describes a response with status code 503, with default header values.

Not available.
*/
type GetAlbumsByIDServiceUnavailable struct {
}

// IsSuccess returns true when this get albums by Id service unavailable response has a 2xx status code
func (o *GetAlbumsByIDServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get albums by Id service unavailable response has a 3xx status code
func (o *GetAlbumsByIDServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get albums by Id service unavailable response has a 4xx status code
func (o *GetAlbumsByIDServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this get albums by Id service unavailable response has a 5xx status code
func (o *GetAlbumsByIDServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this get albums by Id service unavailable response a status code equal to that given
func (o *GetAlbumsByIDServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

func (o *GetAlbumsByIDServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums/{album_id}][%d] getAlbumsByIdServiceUnavailable ", 503)
}

func (o *GetAlbumsByIDServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums/{album_id}][%d] getAlbumsByIdServiceUnavailable ", 503)
}

func (o *GetAlbumsByIDServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
