// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tupyy/gophoto/models"
)

// GetAlbumsReader is a Reader for the GetAlbums structure.
type GetAlbumsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAlbumsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAlbumsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAlbumsOK creates a GetAlbumsOK with default headers values
func NewGetAlbumsOK() *GetAlbumsOK {
	return &GetAlbumsOK{}
}

/* GetAlbumsOK describes a response with status code 200, with default header values.

list of albums owned by or shared with the user
*/
type GetAlbumsOK struct {
	Payload *models.Albums
}

// IsSuccess returns true when this get albums o k response has a 2xx status code
func (o *GetAlbumsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get albums o k response has a 3xx status code
func (o *GetAlbumsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get albums o k response has a 4xx status code
func (o *GetAlbumsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get albums o k response has a 5xx status code
func (o *GetAlbumsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get albums o k response a status code equal to that given
func (o *GetAlbumsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAlbumsOK) Error() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums][%d] getAlbumsOK  %+v", 200, o.Payload)
}

func (o *GetAlbumsOK) String() string {
	return fmt.Sprintf("[GET /api/gphotos/v1/albums][%d] getAlbumsOK  %+v", 200, o.Payload)
}

func (o *GetAlbumsOK) GetPayload() *models.Albums {
	return o.Payload
}

func (o *GetAlbumsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Albums)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
