// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tupyy/gophoto/models"
)

// GetVersionMetadataReader is a Reader for the GetVersionMetadata structure.
type GetVersionMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetVersionMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetVersionMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetVersionMetadataUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetVersionMetadataInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetVersionMetadataOK creates a GetVersionMetadataOK with default headers values
func NewGetVersionMetadataOK() *GetVersionMetadataOK {
	return &GetVersionMetadataOK{}
}

/* GetVersionMetadataOK describes a response with status code 200, with default header values.

version metadata
*/
type GetVersionMetadataOK struct {
	Payload *models.VersionMetadata
}

// IsSuccess returns true when this get version metadata o k response has a 2xx status code
func (o *GetVersionMetadataOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get version metadata o k response has a 3xx status code
func (o *GetVersionMetadataOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get version metadata o k response has a 4xx status code
func (o *GetVersionMetadataOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get version metadata o k response has a 5xx status code
func (o *GetVersionMetadataOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get version metadata o k response a status code equal to that given
func (o *GetVersionMetadataOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetVersionMetadataOK) Error() string {
	return fmt.Sprintf("[GET /api/gphotos/v1][%d] getVersionMetadataOK  %+v", 200, o.Payload)
}

func (o *GetVersionMetadataOK) String() string {
	return fmt.Sprintf("[GET /api/gphotos/v1][%d] getVersionMetadataOK  %+v", 200, o.Payload)
}

func (o *GetVersionMetadataOK) GetPayload() *models.VersionMetadata {
	return o.Payload
}

func (o *GetVersionMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VersionMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetVersionMetadataUnauthorized creates a GetVersionMetadataUnauthorized with default headers values
func NewGetVersionMetadataUnauthorized() *GetVersionMetadataUnauthorized {
	return &GetVersionMetadataUnauthorized{}
}

/* GetVersionMetadataUnauthorized describes a response with status code 401, with default header values.

Not authenticated
*/
type GetVersionMetadataUnauthorized struct {
}

// IsSuccess returns true when this get version metadata unauthorized response has a 2xx status code
func (o *GetVersionMetadataUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get version metadata unauthorized response has a 3xx status code
func (o *GetVersionMetadataUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get version metadata unauthorized response has a 4xx status code
func (o *GetVersionMetadataUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get version metadata unauthorized response has a 5xx status code
func (o *GetVersionMetadataUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get version metadata unauthorized response a status code equal to that given
func (o *GetVersionMetadataUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetVersionMetadataUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/gphotos/v1][%d] getVersionMetadataUnauthorized ", 401)
}

func (o *GetVersionMetadataUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/gphotos/v1][%d] getVersionMetadataUnauthorized ", 401)
}

func (o *GetVersionMetadataUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetVersionMetadataInternalServerError creates a GetVersionMetadataInternalServerError with default headers values
func NewGetVersionMetadataInternalServerError() *GetVersionMetadataInternalServerError {
	return &GetVersionMetadataInternalServerError{}
}

/* GetVersionMetadataInternalServerError describes a response with status code 500, with default header values.

unexpected error occured
*/
type GetVersionMetadataInternalServerError struct {
}

// IsSuccess returns true when this get version metadata internal server error response has a 2xx status code
func (o *GetVersionMetadataInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get version metadata internal server error response has a 3xx status code
func (o *GetVersionMetadataInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get version metadata internal server error response has a 4xx status code
func (o *GetVersionMetadataInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get version metadata internal server error response has a 5xx status code
func (o *GetVersionMetadataInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get version metadata internal server error response a status code equal to that given
func (o *GetVersionMetadataInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetVersionMetadataInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/gphotos/v1][%d] getVersionMetadataInternalServerError ", 500)
}

func (o *GetVersionMetadataInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/gphotos/v1][%d] getVersionMetadataInternalServerError ", 500)
}

func (o *GetVersionMetadataInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
