// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Tag tag
//
// swagger:model Tag
type Tag struct {
	ObjectReference

	// albums
	// Required: true
	Albums []*TagAlbumsItems0 `json:"albums"`

	// color of the tag in hex format
	Color string `json:"color,omitempty"`

	// name of the tag
	// Required: true
	Name *string `json:"name"`

	// tag's owner id
	// Required: true
	UserID *string `json:"user_id"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Tag) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ObjectReference
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ObjectReference = aO0

	// AO1
	var dataAO1 struct {
		Albums []*TagAlbumsItems0 `json:"albums"`

		Color string `json:"color,omitempty"`

		Name *string `json:"name"`

		UserID *string `json:"user_id"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Albums = dataAO1.Albums

	m.Color = dataAO1.Color

	m.Name = dataAO1.Name

	m.UserID = dataAO1.UserID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Tag) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.ObjectReference)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Albums []*TagAlbumsItems0 `json:"albums"`

		Color string `json:"color,omitempty"`

		Name *string `json:"name"`

		UserID *string `json:"user_id"`
	}

	dataAO1.Albums = m.Albums

	dataAO1.Color = m.Color

	dataAO1.Name = m.Name

	dataAO1.UserID = m.UserID

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tag
func (m *Tag) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ObjectReference
	if err := m.ObjectReference.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAlbums(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tag) validateAlbums(formats strfmt.Registry) error {

	if err := validate.Required("albums", "body", m.Albums); err != nil {
		return err
	}

	for i := 0; i < len(m.Albums); i++ {
		if swag.IsZero(m.Albums[i]) { // not required
			continue
		}

		if m.Albums[i] != nil {
			if err := m.Albums[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("albums" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("albums" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Tag) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *Tag) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this tag based on the context it is used
func (m *Tag) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ObjectReference
	if err := m.ObjectReference.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAlbums(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tag) contextValidateAlbums(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Albums); i++ {

		if m.Albums[i] != nil {
			if err := m.Albums[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("albums" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("albums" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Tag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tag) UnmarshalBinary(b []byte) error {
	var res Tag
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// TagAlbumsItems0 tag albums items0
//
// swagger:model TagAlbumsItems0
type TagAlbumsItems0 struct {
	ObjectReference
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TagAlbumsItems0) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ObjectReference
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ObjectReference = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TagAlbumsItems0) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ObjectReference)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this tag albums items0
func (m *TagAlbumsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ObjectReference
	if err := m.ObjectReference.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this tag albums items0 based on the context it is used
func (m *TagAlbumsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ObjectReference
	if err := m.ObjectReference.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TagAlbumsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TagAlbumsItems0) UnmarshalBinary(b []byte) error {
	var res TagAlbumsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
